apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ottocoffee
spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: enessermaxhaj/enescoffe-frontend:1.2
          ports:
            - containerPort: 80
